name: Build Extreme Gaming Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libstdc++6 git wget python3 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev flex bison

      - name: Download Toolchain & Source
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang
          git clone --depth=1 https://github.com/LineageOS/android_kernel_xiaomi_vayu kernel-source

      - name: Build Kernel
        run: |
          export PATH=$(pwd)/clang/bin:$PATH
          cd kernel-source
          make O=out ARCH=arm64 vendor/vayu_user_defconfig
          make -j$(nproc --all) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-PocoX3Pro-Vayu
          path: kernel-source/out/arch/arm64/boot/Image.gz-dtb
          
